name: Discord PR Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR info to Discord
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "🛠 Новий Pull Request: **${{ github.event.pull_request.title }}** від **${{ github.actor }}** → ${{ github.event.pull_request.html_url }}"
